###
# Registration
POST https://localhost:8443/api/rest/users/register
Content-Type: application/json

{
  "username": {{$uuid}},
  "password": "top-secret"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

POST https://localhost:8443/api/rest/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "god"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

GET https://server.local:8443/api/cards.getAll
Cookie: z/iU0+EfCgygAvNrojB7SFsvhNPcgSSD+6F1C9fCpADAstPxdG6+ZrlzXtntWv3mfcDYwS5PAISPJWPjt1GCbg==

###
GET https://server.local:8443/api/cards.getAll
Authorization: z/iU0+EfCgygAvNrojB7SFsvhNPcgSSD+6F1C9fCpADAstPxdG6+ZrlzXtntWv3mfcDYwS5PAISPJWPjt1GCbg==

###
GET https://localhost:8443/api/cards.getAll
Authorization: Basic YWRtaW46Z29k

###
POST https://server.local:8443/api/cards.transfer
Authorization: 6NSb+2kcdKF44ut4iBu+dm6YLu6pakWapvxHtxqaPgMr5iRhox/HlhBerAZMILPjwnRtXms+zDfVTLCsao9nuw==
Content-Type: application/json

{
  "fromCard": "**** *888",
  "username": "student",
  "toCard": "**** *999",
  "amount": 10000
}

###
POST https://localhost:8443/api/reset_password
Authorization: 6NSb+2kcdKF44ut4iBu+dm6YLu6pakWapvxHtxqaPgMr5iRhox/HlhBerAZMILPjwnRtXms+zDfVTLCsao9nuw==
Content-Type: application/json

{
  "code": 301845,
  "password": "topsecret"
}