###
# Registration
POST https://localhost:8443/api/rest/users/register
Content-Type: application/json

{
  "username": {{$uuid}},
  "password": "top-secret"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

POST https://localhost:8443/api/rest/users/login
Content-Type: application/json

{
  "username": "student",
  "password": "qwery123"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

GET https://localhost:8443/api/cards.getAll
Authorization: 6NSb+2kcdKF44ut4iBu+dm6YLu6pakWapvxHtxqaPgMr5iRhox/HlhBerAZMILPjwnRtXms+zDfVTLCsao9nuw==

###
GET https://localhost:8443/api/cards.getAll
Authorization: Uvmbsv1hW8pN0O0BoGpPPjdzKy6xJ2dmJKUkVuBlMxNtpp4TSewVVE27mLte7LyyVT+luue3eBZcGn2TEV7WvQ==

###
POST https://localhost:8443/api/cards.transfer
Authorization: 6NSb+2kcdKF44ut4iBu+dm6YLu6pakWapvxHtxqaPgMr5iRhox/HlhBerAZMILPjwnRtXms+zDfVTLCsao9nuw==
Content-Type: application/json

{
  "fromCard": "**** *888",
  "username": "student",
  "toCard": "**** *999",
  "amount": 10000
}

###
POST https://localhost:8443/api/reset_password
Authorization: 6NSb+2kcdKF44ut4iBu+dm6YLu6pakWapvxHtxqaPgMr5iRhox/HlhBerAZMILPjwnRtXms+zDfVTLCsao9nuw==
Content-Type: application/json

{
  "code": 301845,
  "password": "topsecret"
}